# Generated by Django 4.0.6 on 2022-07-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_excercise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='excercise',
            old_name='artist',
            new_name='Workout',
        ),
    ]
