# Generated by Django 4.0.6 on 2022-07-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_workout_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='workout_name',
        ),
    ]
